spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcs_local?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
      timeout: 3000ms

server:
  port: 8082

logging:
  level:
    cn.masu.dcs: debug
    com.baomidou.mybatisplus: debug

