spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/dcs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 
  data:
    redis:
      host: 
      port: 6379
      password: prodStrongPass
      database: 3
      timeout: 3000ms

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    cn.masu.dcs: info
    com.baomidou.mybatisplus: warn

